export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";

export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";

export const CLEAR_CART = "CLEAR_CART";

export const AUTHENTICATE = "AUTHENTICATE";

export const DEAUTHENTICATE = "DEAUTHENTICATE";

export const OPEN_MODAL = "OPEN_MODAL";

export const CLOSE_MODAL = "CLOSE_MODAL";
